Project_24_02/mysite/myauth/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView


from .views import login_view

app_name = "myauth"

urlpatterns = [
    path("login/", LoginView.as_view(template_name="myauth/login.html"), name="login"),
]

Project_24_02/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('req/', include('requestdataapp.urls')),
    path('shop/', include('shopapp.urls')),
    path('myauth/', include('myauth.urls')),
]

Project_24_02/mysite/shopapp/urls.py
from django.urls import path

from .views import (
    ShopIndexView,
    GroupsListView,
    ProductDetailsView,
    ProductListView,
    OrdersListView,
    OrderDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    OrderCreateView,
    OrderUpdateView,
    OrderDeleteView,
)

app_name = "shopapp"

urlpatterns = [
    path("", ShopIndexView.as_view(), name="index"),
    path("groups/", GroupsListView.as_view(), name="groups_list"),
    path("products/", ProductListView.as_view(), name="products_list"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path("products/<int:pk>/", ProductDetailsView.as_view(), name="product_details"),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/archived/", ProductDeleteView.as_view(), name="product_delete"),
    path("orders/", OrdersListView.as_view(), name="orders_list"),
    path("orders/create", OrderCreateView.as_view(), name="order_create"),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name="order_details"),
    path("orders/<int:pk>/update/", OrderUpdateView.as_view(), name="order_update"),
    path("orders/<int:pk>/delete/", OrderDeleteView.as_view(), name="order_delete")

    # path("orders/create", create_order, name="orders_create"),

]

Project_24_02/mysite/shopapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    class Meta:
        ordering = ['name', '-price']
        #db_table = 'tech_products'
        #verbose_name_plural = 'Products'

    name = models.CharField(max_length=100)
    description = models.TextField(null=False, blank=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)

#    @property
#    def description_short(self) -> str:
#        if len(self.description) < 40:
#            return self.description
#       return self.description[:40] + '...'

    def __str__(self):
        return f"Product(pk={self.pk}, name={self.name!r})"

class Order(models.Model):
    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name='orders')

Project_24_02/mysite/shopapp/forms.py
from django.contrib.auth.models import Group
from django import forms
#from django.core import validators
from django.forms import ModelForm

from .models import Product, Order


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name']

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price', 'description', 'discount']

class OrderForm(forms.ModelForm):
     class Meta:
         model = Order
         #fields = ['name', 'email', 'phone', 'address']
         fields = ['user', 'products', 'promocode', 'delivery_address']






# class ProductForm(forms.Form):
#     name = forms.CharField(max_length=100)
#     price = forms.DecimalField(min_value=1, max_value=100000, decimal_places=2)
#     description = forms.CharField(
#         label='Product description',
#         widget=forms.Textarea(attrs={'rows': 5, "cols": 100}),
#         validators=[validators.RegexValidator(
#             regex=r"great",
#             message="Description must be great"
#         )]
#     )

Project_24_02/mysite/shopapp/views.py
from _ast import Delete

from django.contrib.messages import success
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from django.shortcuts import render, redirect, reverse, get_object_or_404
from timeit import default_timer
from django.contrib.auth.models import Group
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView

from .models import Product, Order
from .forms import ProductForm, OrderForm, GroupForm

class ShopIndexView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        products = [
            ('Laptop', 1999),
            ('Desktop', 2999),
            ('Smartphone', 999),
        ]
        context = {
            "time_running": default_timer(),
            "products": products,
        }
        return render(request, "shopapp/shop-index.html", context=context)

class GroupsListView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        context = {
            "form": GroupForm(),
            "groups": Group.objects.prefetch_related('permissions').all(),
        }
        return render(request, "shopapp/groups-list.html", context=context)

    def post(self, request: HttpRequest) -> HttpResponse:
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect(request.path)

class ProductDetailsView(DetailView):
    template_name = 'shopapp/product_detail.html'
    model = Product
    context_object_name = "product"

class ProductListView(ListView):
    template = "shopapp/products_list.html"
    # model = Product
    context_object_name = "products"
    queryset = Product.objects.filter(archived=False)

class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("shopapp:products_list")
    def form_valid(self, form):
        success_url = self.success_url
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)

class ProductCreateView(CreateView):
    model = Product
    fields = "name", "price", "description", "discount"
    success_url = reverse_lazy("shopapp:products_list")

class ProductUpdateView(UpdateView):
    model = Product
    fields = "name", "price", "description", "discount"
    template_name_suffix = "_update_form"
    def get_success_url(self):
        return reverse("shopapp:product_details",
                       kwargs={"pk": self.object.pk})

class OrdersListView(ListView):
    queryset = (
        Order.objects
        .select_related("user")
        .prefetch_related("products")
    )

class OrderDetailView(DetailView):
    queryset = (
        Order.objects
        .select_related("user")
        .prefetch_related("products")
    )

class OrderCreateView(CreateView):
    model = Order
    fields = 'user', 'products', 'promocode', 'delivery_address'
    success_url = reverse_lazy("shopapp:orders_list")

class OrderUpdateView(UpdateView):
    model = Order
    fields = ['user', 'products', 'promocode', 'delivery_address']
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse("shopapp:order_details",
                       kwargs={"pk": self.object.pk})

class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy("shopapp:orders_list")
    def form_valid(self, form):
        success_url = self.success_url
        self.object.delete()
        return HttpResponseRedirect(success_url)

Project_24_02/mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {%  block title %}
            Base Title
        {%  endblock %}
    </title>
</head>
<body>
{%  block body %}
Base body
{%  endblock %}

<div>
{%  now 'H:i' %}
</div>
<div>
{%  now 'l' as current_weekday %}
        Today is {{ current_weekday }}
</div>
</body>
</html>

Project_24_02/mysite/shopapp/templates/shopapp/create-order.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create order
{% endblock %}

{% block body %}
    <h1>Create a new order</h1>
    <div>
        <form method="post">
            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit">
                Create
            </button>
        </form>
    </div>

    <div>
        <a href="{% url 'shopapp:orders_list' %}"
        >Back to orders list</a>
    </div>
{% endblock %}

Project_24_02/mysite/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Groups List
{% endblock %}

{% block body %}
    <h1>Groups:</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">
                Create
            </button>
        </form>
    </div>

    <div>
    {% if not groups%}
        <h3>No groups yet</h3>
    {% else %}
        <ul>
            {% for group in groups %}
            <li>
                <div>{{ group.name }}</div>
                <ul>
                    {%  for permission in group.permissions.all %}
                        <li>{{ permission.name }}
                        (<code>{{ permission.codename }}</code>)
                        </li>
                    {%  endfor %}
                </ul>
            </li>
            {% endfor %}
        </ul>
    {% endif %}

    </div>
{% endblock %}

Project_24_02/mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm delete {{ object.name }}
{% endblock %}

{% block body %}
    <h1>Are you sure to delete {{ object.name }}</h1>
        <br>
        <div>
            <a href="{% url 'shopapp:order_details' pk=object.pk %}"
            >Back to order #{{ object.pk }}</a>
        </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Delete</button>
        </form>
    </div>


{% endblock %}

Project_24_02/mysite/shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Order #{{ object.pk }} details
{% endblock %}

{% block body %}
    <h1>Order #{{ object.pk }}</h1>

    <div>
        <p>Order by {% firstof object.user.first_name object.user.username %}</p>
        <p>Promo-code: <code>{{ object.promocode }}</code></p>
        <p>Delivery address: {{ object.address }}</p>
        <div>
            Products in order:
            <ul>
                {% for product in object.products.all %}
                    <li>{{ product.name }} for ${{ product.price }}</li>
                {% endfor %}

            </ul>
        </div>
    </div>

    <div>
        <a href="{% url 'shopapp:orders_list' %}">Back to orders</a>
    </div>

    <div>
        <a href="{% url 'shopapp:order_update' pk=object.pk %}">Update order</a>
    </div>

    <div>
        <a href="{% url 'shopapp:order_delete' pk=object.pk %}">Delete order</a>
    </div>


{% endblock %}

Project_24_02/mysite/shopapp/templates/shopapp/order_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create order
{% endblock %}

{% block body %}
    <h1>Create order</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
        <div>
            <a href="{% url 'shopapp:orders_list' %}">Back to order list</a>
        </div>

{% endblock %}

Project_24_02/mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Orders List
{% endblock %}

{% block body %}
  <h1>Orders:</h1>
    {% if object_list %}
        <div>
            {% for order in object_list %}
                <div>
                    <p><a href="{% url "shopapp:order_details" pk=order.pk %}"
                        >Details #{{ order.pk }}</a></p>
                    <p>Order by {{ order.user.username }}</p>
                    <p>Promo-code: <code>{{ order.promocode }}</code></p>
                    <p>Delivery address: {{ order.address }}</p>
                <div>
                    Products in order:
                </div>
                    <ul>
                        {% for product in order.products.all %}
                            <li>{{ product.name }} for ${{ product.price }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <h3>No orders yet</h3>
    {% endif %}
    <div></div>
{% endblock %}

Project_24_02/mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm archived {{ object.name }}
{% endblock %}

{% block body %}
    <h1>Are you sure to archived {{ object.name }}</h1>
        <br>
        <div>
            <a href="{% url 'shopapp:product_details' pk=object.pk %}"
            >Back to product #{{ object.pk }}</a>
        </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">archived</button>
        </form>
    </div>


{% endblock %}

Project_24_02/mysite/shopapp/templates/shopapp/product_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Product #{{ product.pk }}
{% endblock %}

{% block body %}
    <h1>
    Product <strong>{{ product.name }}</strong>
    </h1>
        <div>
            <div>Description: <em>{{ product.description }}</em></div>
            <div>Price: {{ product.price }}</div>
            <div>Discount: {{ product.discount }}</div>
            <div>Archived: {{ product.archived }}</div>
        </div>

        <div>
            <a href="{% url 'shopapp:product_update' pk=product.pk %}">Update product</a>
        </div>

        <div>
            <a href="{% url 'shopapp:product_delete' pk=product.pk %}">Archived product</a>
        </div>

        <div>
            <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
        </div>

{% endblock %}

Project_24_02/mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>Create product</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
        <div>
            <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
        </div>



{% endblock %}

Project_24_02/mysite/shopapp/templates/shopapp/product_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Products List
{% endblock %}

{% block body %}
    <h1>
    Products
    </h1>

    {% if products %}
        <div>
            {% for product in products %}
                <div>
                    <p><a href="{% url 'shopapp:product_details' pk=product.pk %}"
                    >Name {{ product.name }}</a></p>
                    <p>Price: {{ product.price }}</p>
                    <p>Discount: {% firstof product.discount 'no discount' %}</p>

                </div>
            {% endfor %}
        </div>
    {%  else %}
        <h3>No products yet</h3>
    {% endif %}

    <div>
        <a href="{% url 'shopapp:product_create' %}"
           >Create a new product</a>
    </div>


{% endblock %}

Project_24_02/mysite/shopapp/templates/shopapp/product_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Update product
{% endblock %}

{% block body %}
    <h1>Update product</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>
        <div>
            <a href="{% url 'shopapp:product_details' pk=object.pk %}"
            >Back to product #{{ object.pk }}</a>
        </div>



{% endblock %}

Project_24_02/mysite/shopapp/templates/shopapp/products_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Products List
{% endblock %}

{% block body %}
    <h1>
    Products
    </h1>

    {% if products %}
        <div>
            {% for product in products %}
                <div>
                    <p>Name: {{ product.name }}</p>
                    <p>Price: {{ product.price }}</p>
                    <p>Discount: {% firstof product.discount 'no discount' %}</p>

                </div>
            {% endfor %}
        </div>
    {%  else %}
        <h3>No products yet</h3>
    {% endif %}

    <div>
        <a href="{% url 'shopapp:product_create' %}"
           >Create a new product</a>
    </div>


{% endblock %}

Project_24_02/mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Shop Index
{% endblock %}

{% block body %}
    <h1>
    Hello Shop Index
    </h1>

    <div>
        <ul>
            {% for name, price in products %}
                <li>
                {{ name }} for ${{ price }}
                </li>
                <span>{{  name|length_is:'7' }}</span>
                {% empty%}
                no products here

            {% endfor %}

        </ul>
    </div>

    <div>
    Time running: {{ time_running }}
    </div>
<div>
{%  lorem 3 p random %}
</div>

{% endblock %}